import { defineKatexSetup } from '@slidev/types'

export default defineKatexSetup(() => {
  return {
    maxExpand: 2000,
    macros: {
      "\\vA": "{\\mathbf A}",
      "\\vB": "{\\mathbf B}",
      "\\vC": "{\\mathbf C}",
      "\\vD": "{\\mathbf D}",
      "\\vE": "{\\mathbf E}",
      "\\vF": "{\\mathbf F}",
      "\\vG": "{\\mathbf G}",
      "\\vH": "{\\mathbf H}",
      "\\vI": "{\\mathbf I}",
      "\\vJ": "{\\mathbf J}",
      "\\vK": "{\\mathbf K}",
      "\\vL": "{\\mathbf L}",
      "\\vM": "{\\mathbf M}",
      "\\vN": "{\\mathbf N}",
      "\\vO": "{\\mathbf O}",
      "\\vP": "{\\mathbf P}",
      "\\vQ": "{\\mathbf Q}",
      "\\vR": "{\\mathbf R}",
      "\\vS": "{\\mathbf S}",
      "\\vT": "{\\mathbf T}",
      "\\vU": "{\\mathbf U}",
      "\\vV": "{\\mathbf V}",
      "\\vW": "{\\mathbf W}",
      "\\vX": "{\\mathbf X}",
      "\\vY": "{\\mathbf Y}",
      "\\vZ": "{\\mathbf Z}",
      "\\va": "{\\mathbf a}",
      "\\vb": "{\\mathbf b}",
      "\\vc": "{\\mathbf c}",
      "\\vd": "{\\mathbf d}",
      "\\ve": "{\\mathbf e}",
      "\\vf": "{\\mathbf f}",
      "\\vg": "{\\mathbf g}",
      "\\vh": "{\\mathbf h}",
      "\\vi": "{\\mathbf i}",
      "\\vj": "{\\mathbf j}",
      "\\vk": "{\\mathbf k}",
      "\\vl": "{\\mathbf l}",
      "\\vm": "{\\mathbf m}",
      "\\vn": "{\\mathbf n}",
      "\\vo": "{\\mathbf o}",
      "\\vp": "{\\mathbf p}",
      "\\vq": "{\\mathbf q}",
      "\\vr": "{\\mathbf r}",
      "\\vs": "{\\mathbf s}",
      "\\vt": "{\\mathbf t}",
      "\\vu": "{\\mathbf u}",
      "\\vv": "{\\mathbf v}",
      "\\vw": "{\\mathbf w}",
      "\\vx": "{\\mathbf x}",
      "\\vy": "{\\mathbf y}",
      "\\vz": "{\\mathbf z}",
      "\\E": "\\mathbb{E}",
      "\\vzero": "{\\mathbf 0}",
      "\\vone": "{\\mathbf 1}",
      "\\cov": "{\\rm Cov}",
      "\\var": "{\\rm Var}",
      "\\d": "{\\rm d}",
      "\\cond": "\\,\\vert\\,",
      "\\data": "{\\cal D}",
      "\\vtheta": "{\\bm \\theta}",
      "\\vmu": "{\\bm \\mu}",
      "\\vSigma": "{\\bm \\Sigma}"
    }
  }
})
